### ISSUE TITLE
Engine::Drop method does not work.

### ISSUE THREAD

**Issue by AFKL-CUIT** [newpanjing/gofound#12]
# 环境配置
源码编译（`go get & go build`）后，将二进制文件放入docker内。
```Dockerfile
FROM ubuntu:20.04

COPY ./gofound /app/gofound
RUN mkdir /app/data &&\
    chmod 555 /app/gofound

WORKDIR /app

EXPOSE 5678

CMD ["./gofound", "--addr=:5678", "--data=./data"]
```

# 发生了什么
删除数据库后，虽然数据库的记录已经在内存中删除了，但对应生成的文件并没有删除。
![](https://user-images.githubusercontent.com/56114673/168744866-3d5e1897-5acf-4a95-8092-0f10d1a1e53b.png)

似乎是[Engine::Drop方法](https://github.com/newpanjing/gofound/blob/f50a0aebfb49bc31bd0be9175a65cb8a01d22a02/searcher/engine.go#L547)中的代码存在问题。

且其中的第551行不知道为什么要每次都要执行`os.Remove(e.IndexPath)`，应该可以优化一下。

# 预期结果
删除数据库后，内存中的记录删除以外，对应的数据库文件也删除。

# 其他
我不确定这是否是预期行为，但个人感觉应该是一个bug。

**Comment by newpanjing** [comment]
没错，这就是一个bug，预计下个版本修复。

**Comment by newpanjing** [comment]
没错，这就是一个bug，预计下个版本修复。

**Comment by newpanjing** [comment]
https://github.com/newpanjing/gofound/releases/tag/v1.1.5

已经修复 并发布新版本

**Comment by zhangchunlin** [comment]
可是用最新的main分支，然后用python测试代码 https://github.com/newpanjing/gofound-python/blob/master/README.md 测试还是无法删除成功。
