### ISSUE TITLE
通过 API 添加完数据之后, 在 admin 查询报错! runtime error: invalid memory address

### ISSUE THREAD

**Issue by Wickscc** [newpanjing/gofound#29]
![image](https://user-images.githubusercontent.com/29065905/173477277-9ff42172-24b4-4e0c-88d4-5f81a05f1449.png)

添加完索引过后时常会抛出这个异常
启动未添加任何参数

![image](https://user-images.githubusercontent.com/29065905/173477425-1c93040c-9886-44bc-b645-cc69a5917f82.png)

**Comment by XiaoK29** [comment]
用的那个版本的

> ![图片](https://user-images.githubusercontent.com/29065905/173477277-9ff42172-24b4-4e0c-88d4-5f81a05f1449.png)
> 
> 添加完索引后时常会抛出这个异常 启动未添加任何参数
> 
> ![图片](https://user-images.githubusercontent.com/29065905/173477425-1c93040c-9886-44bc-b645-cc69a5917f82.png)

**Comment by Wickscc** [comment]
> 用那个版本的
> 
> > ![图片](https://user-images.githubusercontent.com/29065905/173477277-9ff42172-24b4-4e0c-88d4-5f81a05f1449.png)
> > 添加索引完成后时常会抛出这个异常 未启动的任何参数
> > ![图片](https://user-images.githubusercontent.com/29065905/173477425-1c93040c-9886-44bc-b645-cc69a5917f82.png)

1.1.4

**Comment by XiaoK29** [comment]
> > 用那个版本的
> > > ![图片](https://user-images.githubusercontent.com/29065905/173477277-9ff42172-24b4-4e0c-88d4-5f81a05f1449.png)
> > > 添加索引完成后时常会抛出这个异常 未启动的任何参数
> > > ![图片](https://user-images.githubusercontent.com/29065905/173477425-1c93040c-9886-44bc-b645-cc69a5917f82.png)
> 
> 1.1.4

更新到1.1.5哦，这个bug在1.1.5已经修复
