### ISSUE TITLE
考虑支持系统环境变量参数配置？

### ISSUE THREAD

**Issue by gotoeasy** [newpanjing/gofound#40]
如今都是容器化部署，命令行参数配置较为繁琐，文件配置也不够灵活，将会有有众多的个性化参数出现。

各参数提供默认值，以环境变量配置以可替换化，这是比较灵活的方式，容器化部署也会很方便，请考虑，预祝越做越好！

**Comment by XiaoK29** [comment]
> 如今都是容器化部署，命令行参数配置较为繁琐，文件配置也不够灵活，将会有有众多的个性化参数出现。
> 
> 各参数提供默认值，以环境变量配置以可替换化，这是比较灵活的方式，容器化部署也会很方便，请考虑，预祝越做越好！

支持环境变量还是使用yaml文件管理呢？

**Comment by gotoeasy** [comment]
> 支持环境变量还是使用yaml文件管理呢？

环境变量，即简单又灵活

**Comment by newpanjing** [comment]
这是个好主意， @XiaoK29 咱们有空的时候支持下这个。
